### ISSUE TITLE
Recovery seed should be generated on the client side

### ISSUE THREAD

**Issue by ghost** [roccstar/mysiacoin#1]
I'm probably not alone in thinking that the "Private Recovery Seed" should never be seen by the server.

Take a look at something like this: [bitcoinpaperwallet.com:generate-wallet](https://bitcoinpaperwallet.com/bitcoinpaperwallet/generate-wallet.html) where the keys are all generated right in your browser.

**Comment by johnathanhowell** [comment]
It is probably possible to do this by compiling `sia-coldstorage` with gopherjs: https://github.com/gopherjs/gopherjs

**Comment by therocco** [comment]
Work has already started on porting the coldstorage seed generator to javascript (https://github.com/roccstar/sia-coldstorage-json/blob/master/build/sia-coldstorage-json.min.js). The main issue is the size of the script which is coming close to 2MB. Currently working on a way to slim that down to create a better experience for individuals with slower connections.

**Comment by therocco** [comment]
New site update has launched. All seed generation is done in the client side.
